# Main working directory
workdir: "workflows"

# Store all FASTA files here
filedir: "workflows/workflow/fasta"

#Rebuild the full list of EC numbers
update_ec_nums : False

#List of columns to create an annotation file for - if this file is missing or empty it will include all columns in the annotation file
annotation_cols : "config/annotation_cols.txt"

# # Each FASTA file needs an according .subset file in this folder (test1.fasta -> test1.subset)
# subdir: "workflows/workflow/subset_rules"

# # annotation_cols: ['Taxonomic_lineage_PHYLUM', 'Taxonomic_lineage_SUPERKINGDOM',
# # 'KARI_Class', 'Loop_Length', 'Cross-reference_SUPFAM',
# # Cross-reference_Pfam', 'Cross-reference_OMA', 'BRENDA_KM', 'EC_number']

# annotation_cols: ['Taxonomic_lineage_PHYLUM', 'Taxonomic_lineage_SUPERKINGDOM',
# 'KARI_Class', 'Loop_Length', 'Binding_positions_alignment_residues']

# ancestor_cols: ['Acidic_Binding_alignment : Acidic_residue']

# # active_datasets : [
# #   'uniprot_ec_1_1_1_86_AND_uniprot_ec_1_1_1_382_AND_uniprot_ec_1_1_1_383',
# # 'uniprot_ec_2_2_1_6',
# # 'uniprot_ec_4_2_1_9',
# # 'uniprot_ec_4_2_1_9_small_example']

# # active_datasets : ['klebsiella_ncbi']

# # active_datasets : [
# # 'uniprot_ec_3_2_1_21']

# active_datasets : ['terpene_synthases_90_1e-75_motif_confirmed_long_N_C_removed_missing_motif_removed_truncated_DSE_extension_removed_further_edits_cropped']

# brenda_cols : ['KM', 'TN']

# outgroup : ['MOTIF_RFDDR' : True]

# key_annotation_cols : ['BRENDA_KM', 'Cross_reference_InterPro', 'Cross_reference_Pfam', 'Cross_reference_PROSITE', 'ChEBI_Cofactor',
# 'Gene_ontology_molecular_function', 'MOTIF_SPVEY',  'MOTIF_RFDDR']

#Filtering parameters 
# threshold = 0.5, how similar can two IP/SMART tags be
# min number of entries = 1 
#the minimum number of entries for a particular tag needed to be included 
filter_parameters: ["0.2", "0"]

#which row in InterPro matrix to match entries to 
row_num: "0"